In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as mplt
import matplotlib as plt
import datetime as dati

In [8]:
dataset = pd.read_csv("/home/federico/Git/datos-tp2-2c2020/data/original/Entrenamiento.csv", parse_dates = ['Account_Created_Date', 'Opportunity_Created_Date',
                                                           'Planned_Delivery_Start_Date', 'Planned_Delivery_End_Date',
                                                           'Quote_Expiry_Date', 'Last_Modified_Date','Last_Activity' ])
# Limpio registros con muchos datos faltantes o inutiles
dataset = dataset.drop(columns= ['Prod_Category_A','Product_Category_B','Actual_Delivery_Date','Submitted_for_Approval','Last_Activity','Price','Currency','Brand','Size','Product_Type'])
dataset.dtypes

ID                                             int64
Region                                        object
Territory                                     object
Pricing, Delivery_Terms_Quote_Appr             int64
Pricing, Delivery_Terms_Approved               int64
Bureaucratic_Code_0_Approval                   int64
Bureaucratic_Code_0_Approved                   int64
Bureaucratic_Code                             object
Account_Created_Date                  datetime64[ns]
Source                                        object
Billing_Country                               object
Account_Name                                  object
Opportunity_Name                              object
Opportunity_ID                                 int64
Sales_Contract_No                             object
Account_Owner                                 object
Opportunity_Owner                             object
Account_Type                                  object
Opportunity_Type                              object
Quote_Type                                    object
Delivery_Terms                                object
Opportunity_Created_Date              datetime64[ns]
Quote_Expiry_Date                     datetime64[ns]
Last_Modified_Date                    datetime64[ns]
Last_Modified_By                              object
Product_Family                                object
Product_Name                                  object
ASP_Currency                                  object
ASP                                          float64
ASP_(converted)_Currency                      object
ASP_(converted)                              float64
Planned_Delivery_Start_Date           datetime64[ns]
Planned_Delivery_End_Date             datetime64[ns]
Month                                         object
Delivery_Quarter                              object
Delivery_Year                                  int64
TRF                                            int64
Total_Amount_Currency                         object
Total_Amount                                 float64
Total_Taxable_Amount_Currency                 object
Total_Taxable_Amount                         float64
Stage                                         object
dtype: object

In [9]:
#limpio los datos no finalzizados
dataset = dataset.loc[(dataset['Stage']== 'Closed Won') | (dataset['Stage']== 'Closed Lost')]
dataset['Stage'].value_counts()

Closed Won     9533
Closed Lost    7350
Name: Stage, dtype: int64

# Convertir mondeas

In [10]:
dataset['conversion'] = dataset['ASP_(converted)']/dataset['ASP']

cotizacion = dataset.groupby(['ASP_Currency', 'Opportunity_Created_Date']).agg({'conversion': 'mean'}).reset_index()
#print(dataset[dataset['Stage']== 'Closed Won']['conversion'].value_counts())
cotizacion = cotizacion.rename(columns = {'conversion': 'conversion_diaria'})
cotizacion

dataset= dataset.merge(cotizacion, on = ['ASP_Currency', 'Opportunity_Created_Date'], how = 'left')

dataset

,ID,Region,Territory,"Pricing, Delivery_Terms_Quote_Appr","Pricing, Delivery_Terms_Approved",Bureaucratic_Code_0_Approval,Bureaucratic_Code_0_Approved,Bureaucratic_Code,Account_Created_Date,Source,...,Delivery_Quarter,Delivery_Year,TRF,Total_Amount_Currency,Total_Amount,Total_Taxable_Amount_Currency,Total_Taxable_Amount,Stage,conversion,conversion_diaria
0,27761,EMEA,None,1,1,1,1,Bureaucratic_Code_4,2015-06-16,None,...,Q2,2016,10,EUR,5272800.00,EUR,5272800.00,Closed Lost,1.131096,1.131095
1,27760,EMEA,None,0,0,0,0,Bureaucratic_Code_4,2015-06-16,None,...,Q1,2016,0,EUR,48230.00,EUR,48230.00,Closed Won,1.131094,1.131095
2,27446,Americas,NW America,0,0,0,0,Bureaucratic_Code_4,2015-04-21,Source_7,...,Q1,2016,0,USD,83865.60,USD,83865.60,Closed Won,1.000000,1.000000
3,16808,Americas,NW America,1,0,1,0,Bureaucratic_Code_5,2013-07-27,Source_11,...,Q1,2018,14,USD,7421881.50,USD,7421881.50,Closed Lost,1.000000,1.000000
4,16805,Americas,NW America,1,0,1,0,Bureaucratic_Code_5,2013-07-27,Source_11,...,Q1,2018,25,USD,13357192.50,USD,13357192.50,Closed Lost,1.000000,1.000000
5,16802,Americas,NW America,1,0,1,0,Bureaucratic_Code_5,2013-07-27,Source_11,...,Q1,2018,28,USD,14838277.50,USD,14838277.50,Closed Lost,1.000000,1.000000
6,16799,Americas,NW America,1,0,1,0,Bureaucratic_Code_5,2013-07-27,Source_11,...,Q1,2017,7,USD,2659494.60,USD,2659494.60,Closed Lost,1.000000,1.000000
7,27455,Americas,NW America,1,1,1,1,Bureaucratic_Code_4,2015-04-21,Source_7,...,Q1,2016,0,USD,50688.00,USD,50688.00,Closed Won,1.000000,1.000000
8,24353,Japan,None,1,0,0,0,Bureaucratic_Code_5,2015-04-20,None,...,Q1,2016,0,JPY,15600.00,JPY,470400.00,Closed Lost,NaN,0.008990
9,24355,Japan,None,1,0,0,0,Bureaucratic_Code_5,2015-04-20,None,...,Q1,2016,0,JPY,4400.00,JPY,470400.00,Closed Lost,NaN,0.008990
10,24356,Japan,None,1,0,0,0,Bureaucratic_Code_5,2015-04-20,None,...,Q1,2016,0,JPY,6200.00,JPY,470400.00,Closed Lost,NaN,0.008990
11,24357,Japan,None,1,0,0,0,Bureaucratic_Code_5,2015-04-20,None,...,Q1,2016,0,JPY,140000.00,JPY,470400.00,Closed Lost,NaN,0.008990
12,24358,Japan,None,1,0,0,0,Bureaucratic_Code_5,2015-04-20,None,...,Q1,2016,0,JPY,304200.00,JPY,470400.00,Closed Lost,0.008990,0.008990
13,24420,Japan,None,1,0,0,0,Bureaucratic_Code_5,2015-04-20,None,...,Q1,2016,0,JPY,23400.00,JPY,559320.00,Closed Lost,NaN,0.008990
14,24422,Japan,None,1,0,0,0,Bureaucratic_Code_5,2015-04-20,None,...,Q1,2016,0,JPY,4400.00,JPY,559320.00,Closed Lost,NaN,0.008990
15,24423,Japan,None,1,0,0,0,Bureaucratic_Code_5,2015-04-20,None,...,Q1,2016,0,JPY,6200.00,JPY,559320.00,Closed Lost,NaN,0.008990
16,24424,Japan,None,1,0,0,0,Bureaucratic_Code_5,2015-04-20,None,...,Q1,2016,0,JPY,140000.00,JPY,559320.00,Closed Lost,NaN,0.008990
17,24425,Japan,None,1,0,0,0,Bureaucratic_Code_5,2015-04-20,None,...,Q1,2016,0,JPY,385320.00,JPY,559320.00,Closed Lost,0.008990,0.008990
18,24366,Japan,None,1,0,0,0,Bureaucratic_Code_5,2015-04-20,None,...,Q1,2016,0,JPY,23400.00,JPY,579600.00,Closed Lost,NaN,0.008990
19,24367,Japan,None,1,0,0,0,Bureaucratic_Code_5,2015-04-20,None,...,Q1,2016,0,JPY,4400.00,JPY,579600.00,Closed Lost,NaN,0.008990
20,24368,Japan,None,1,0,0,0,Bureaucratic_Code_5,2015-04-20,None,...,Q1,2016,0,JPY,6200.00,JPY,579600.00,Closed Lost,NaN,0.008990
21,24369,Japan,None,1,0,0,0,Bureaucratic_Code_5,2015-04-20,None,...,Q1,2016,0,JPY,140000.00,JPY,579600.00,Closed Lost,NaN,0.008990
22,24370,Japan,None,1,0,0,0,Bureaucratic_Code_5,2015-04-20,None,...,Q1,2016,0,JPY,405600.00,JPY,579600.00,Closed Lost,0.008990,0.008990
23,28524,APAC,India,1,1,1,1,Bureaucratic_Code_4,2015-10-13,None,...,Q1,2016,3,USD,1621851.00,USD,1621851.00,Closed Won,1.000000,1.000000
24,4915,APAC,India,1,1,0,0,Bureaucratic_Code_4,2015-12-09,None,...,Q1,2016,0,USD,221650.00,USD,221650.00,Closed Lost,1.000000,1.000000
25,24384,Japan,None,1,0,0,0,Bureaucratic_Code_5,2015-04-20,None,...,Q1,2016,0,JPY,4400.00,JPY,1012920.00,Closed Lost,NaN,0.008990
26,24385,Japan,None,1,0,0,0,Bureaucratic_Code_5,2015-04-20,None,...,Q1,2016,0,JPY,1600.00,JPY,1012920.00,Closed Lost,NaN,0.008990
27,24386,Japan,None,1,0,0,0,Bureaucratic_Code_5,2015-04-20,None,...,Q1,2016,0,JPY,31200.00,JPY,1012920.00,Closed Lost,NaN,0.008990
28,24389,Japan,None,1,0,0,0,Bureaucratic_Code_5,2015-04-20,None,...,Q1,2016,0,JPY,6200.00,JPY,1012920.00,Closed Lost,NaN,0.008990
29,24390,Japan,None,1,0,0,0,Bureaucratic_Code_5,2015-04-20,None,...,Q1,2016,0,JPY,280000.00,JPY,1012920.00,Closed Lost,NaN,0.008990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16853,21311,Japan,None,1,1,0,0,Bureaucratic_Code_4,2014-08-22,None,...,Q1,2016,0,JPY,12400.00,JPY,4651580.00,Closed Won,NaN,0.008990
16854,21314,Japan,None,1,1,0,0,Bureaucratic_Code_4,2014-08-22,None,...,Q1,2016,0,JPY,1360000.00,JPY,4651580.00,Closed Won,NaN,0.008990
16855,21317,Japan,None,1,1,0,0,Bureaucratic_Code_4,2014-08-22,None,...,Q1,2016,0,JPY,3222180.00,JPY,4651580.00,Closed Won,0.008990,0.008990
16856,18513,Japan,None,1,1,1,1,Bureaucratic_Code_4,2013-07-28,Source_7,...,Q1,2016,10,USD,6395736.60,USD,6422400.60,Closed Won,1.000000,1.000000
16857,18516,Japan,None,1,1,1,1,Bureaucratic_Code_4,2013-07-28,Source_7,...,Q1,2016,0,USD,13464.00,USD,6422400.60,Closed Won,1.000000,1.000000
16858,18519,Japan,None,1,1,1,1,Bureaucratic_Code_4,2013-07-28,Source_7,...,Q1,2016,0,USD,13200.00,USD,6422400.60,Closed Won,1.000000,1.000000
16859,27689,Japan,None,1,1,0,0,Bureaucratic_Code_4,2015-06-11,Source_3,...,Q1,2016,0,JPY,12194000.00,JPY,12194000.00,Closed Won,0.008990,0.008990
16860,27688,Japan,None,1,1,0,0,Bureaucratic_Code_4,2015-06-11,Source_3,...,Q1,2016,0,JPY,11959500.00,JPY,11959500.00,Closed Won,0.008990,0.008990
16861,19062,Japan,Japan,0,0,0,0,Bureaucratic_Code_4,2013-08-11,Source_11,...,Q1,2016,0,JPY,17537000.00,JPY,17537000.00,Closed Won,0.008990,0.008990
16862,19066,Japan,Japan,1,1,1,1,Bureaucratic_Code_4,2013-08-11,Source_11,...,Q1,2016,0,JPY,13860000.00,JPY,13860000.00,Closed Won,0.008990,0.008990
16863,23920,EMEA,None,0,0,0,0,Bureaucratic_Code_4,2015-03-30,None,...,Q1,2016,0,EUR,107250.00,EUR,107250.00,Closed Won,1.131091,1.131091
16864,19906,EMEA,France,0,0,0,0,Bureaucratic_Code_4,2013-07-27,Source_7,...,Q4,2016,1,EUR,308261.25,EUR,308261.25,Closed Lost,1.131091,1.131093
16865,12703,EMEA,France,1,1,1,1,Bureaucratic_Code_4,2013-07-27,None,...,Q4,2016,15,EUR,7651020.00,EUR,7651020.00,Closed Lost,1.131098,1.131093
16866,28372,Americas,SE America,1,0,1,0,Bureaucratic_Code_5,2015-09-25,Source_7,...,Q2,2016,120,USD,76800640.00,USD,76800640.00,Closed Lost,1.000000,1.000000
16867,17804,EMEA,United Kingdom,1,1,0,0,Bureaucratic_Code_4,2013-10-29,None,...,Q1,2016,4,EUR,2209350.00,EUR,2209350.00,Closed Won,1.131087,1.131093
16868,15785,EMEA,Germany,0,0,0,0,Bureaucratic_Code_4,2013-07-27,None,...,Q1,2016,0,EUR,160650.00,EUR,160650.00,Closed Lost,1.131086,1.131093
16869,15848,EMEA,Germany,0,0,0,0,Bureaucratic_Code_4,2013-07-27,None,...,Q1,2016,0,EUR,56350.00,EUR,112510.00,Closed Won,1.131096,1.131093
16870,15853,EMEA,Germany,0,0,0,0,Bureaucratic_Code_4,2013-07-27,None,...,Q1,2016,0,EUR,56160.00,EUR,112510.00,Closed Won,1.131093,1.131093
16871,17677,EMEA,Germany,0,0,0,0,Bureaucratic_Code_4,2013-07-27,Source_9,...,Q1,2016,0,EUR,59325.00,EUR,528918.75,Closed Won,1.131097,1.131093
16872,17680,EMEA,Germany,0,0,0,0,Bureaucratic_Code_4,2013-07-27,Source_9,...,Q1,2016,0,EUR,56193.75,EUR,528918.75,Closed Won,1.131099,1.131093
16873,17683,EMEA,Germany,0,0,0,0,Bureaucratic_Code_4,2013-07-27,Source_9,...,Q1,2016,1,EUR,413400.00,EUR,528918.75,Closed Won,1.131094,1.131093
16874,28767,EMEA,Germany,1,0,0,0,Bureaucratic_Code_5,2015-12-04,None,...,Q3,2016,3,EUR,1307775.00,EUR,1307775.00,Closed Lost,1.131085,1.131093
16875,18324,EMEA,Norway,1,1,0,0,Bureaucratic_Code_4,2013-07-27,Source_9,...,Q2,2016,1,EUR,401700.00,EUR,401700.00,Closed Won,1.131087,1.131093
16876,20827,Americas,NE America,1,0,0,0,Bureaucratic_Code_5,2014-06-16,None,...,Q4,2016,20,USD,10751580.00,USD,21332500.00,Closed Lost,1.000000,1.000000
16877,20830,Americas,NE America,1,0,0,0,Bureaucratic_Code_5,2014-06-16,None,...,Q4,2016,20,USD,10580920.00,USD,21332500.00,Closed Lost,1.000000,1.000000
16878,8781,EMEA,Austria,1,1,1,1,Bureaucratic_Code_4,2016-01-15,Source_7,...,Q1,2016,0,EUR,103350.00,EUR,299715.00,Closed Won,1.131096,1.131093
16879,8786,EMEA,Austria,1,1,1,1,Bureaucratic_Code_4,2016-01-15,Source_7,...,Q2,2016,0,EUR,93015.00,EUR,299715.00,Closed Won,1.131096,1.131093
16880,8792,EMEA,Austria,1,1,1,1,Bureaucratic_Code_4,2016-01-15,Source_7,...,Q1,2016,0,EUR,103350.00,EUR,299715.00,Closed Won,1.131096,1.131093
16881,28561,Americas,NE America,1,1,1,1,Bureaucratic_Code_4,2015-10-20,None,...,Q2,2016,4,USD,2346796.88,USD,0.00,Closed Lost,1.000000,1.000000
16882,28318,Americas,NE America,1,1,1,1,Bureaucratic_Code_4,2015-09-03,None,...,Q3,2016,40,USD,25603200.00,USD,0.00,Closed Lost,1.000000,1.000000

In [11]:
dataset['conversion'] = dataset.loc[:,'conversion'].fillna(dataset['conversion_diaria'])

In [12]:
dataset = dataset.drop(dataset[dataset['conversion'] == np.inf].index)

In [24]:
dataset.loc[dataset['ASP_Currency'] == 'USD', 'conversion'] = 1
dataset.loc[dataset.ASP_Currency == 'JPY' , 'conversion']= dataset.loc[dataset.ASP_Currency == 'JPY' , 'conversion'].fillna( dataset.loc[dataset.ASP_Currency == 'JPY', 'conversion'].mean())
dataset.loc[dataset.ASP_Currency == 'EUR' , 'conversion']= dataset.loc[dataset.ASP_Currency == 'EUR' , 'conversion'].fillna( dataset.loc[dataset.ASP_Currency == 'EUR', 'conversion'].mean())
dataset['Total_Amount_converted'] = dataset['Total_Amount'] * dataset['conversion']

# diferencias de tiempo

In [14]:
dataset['delta_planed'] = dataset['Planned_Delivery_End_Date'] - dataset['Planned_Delivery_Start_Date']

In [15]:
dataset.dtypes

ID                                              int64
Region                                         object
Territory                                      object
Pricing, Delivery_Terms_Quote_Appr              int64
Pricing, Delivery_Terms_Approved                int64
Bureaucratic_Code_0_Approval                    int64
Bureaucratic_Code_0_Approved                    int64
Bureaucratic_Code                              object
Account_Created_Date                   datetime64[ns]
Source                                         object
Billing_Country                                object
Account_Name                                   object
Opportunity_Name                               object
Opportunity_ID                                  int64
Sales_Contract_No                              object
Account_Owner                                  object
Opportunity_Owner                              object
Account_Type                                   object
Opportunity_Type                               object
Quote_Type                                     object
Delivery_Terms                                 object
Opportunity_Created_Date               datetime64[ns]
Quote_Expiry_Date                      datetime64[ns]
Last_Modified_Date                     datetime64[ns]
Last_Modified_By                               object
Product_Family                                 object
Product_Name                                   object
ASP_Currency                                   object
ASP                                           float64
ASP_(converted)_Currency                       object
ASP_(converted)                               float64
Planned_Delivery_Start_Date            datetime64[ns]
Planned_Delivery_End_Date              datetime64[ns]
Month                                          object
Delivery_Quarter                               object
Delivery_Year                                   int64
TRF                                             int64
Total_Amount_Currency                          object
Total_Amount                                  float64
Total_Taxable_Amount_Currency                  object
Total_Taxable_Amount                          float64
Stage                                          object
conversion                                    float64
conversion_diaria                             float64
Total_Amount_converted                        float64
delta_planed                          timedelta64[ns]
dtype: object

In [16]:
dataset['acount_age'] = dataset['Opportunity_Created_Date'] - dataset['Account_Created_Date']

# features por oportunity ID

In [17]:
#Opportunity_ID
features= ['sum','mean','median','std', 'max', 'min']

dataset_numerico = dataset[['Opportunity_ID','ASP', 'ASP_(converted)', 'TRF', 'Total_Amount', 'Total_Taxable_Amount', 'Total_Amount_converted']]
#ASP                                           float64
#ASP_(converted)                               float64
#TRF                                             int64
#Total_Amount                                  float64
#Total_Taxable_Amount                          float64
#Total_Amount_converted                        float64

features_num= dataset_numerico.groupby('Opportunity_ID').agg(features)
level_0 = features_num.columns.get_level_values(0)
level_1 = features_num.columns.get_level_values(1)
features_num.columns = level_0 + '_' + level_1
features_num.reset_index()
dataset = dataset.join(features_num, on= 'Opportunity_ID', how = 'left')

In [18]:
dataset.dtypes

ID                                             int64
Region                                        object
Territory                                     object
Pricing, Delivery_Terms_Quote_Appr             int64
Pricing, Delivery_Terms_Approved               int64
Bureaucratic_Code_0_Approval                   int64
Bureaucratic_Code_0_Approved                   int64
Bureaucratic_Code                             object
Account_Created_Date                  datetime64[ns]
Source                                        object
Billing_Country                               object
Account_Name                                  object
Opportunity_Name                              object
Opportunity_ID                                 int64
Sales_Contract_No                             object
Account_Owner                                 object
Opportunity_Owner                             object
Account_Type                                  object
Opportunity_Type                              object
Quote_Type                                    object
Delivery_Terms                                object
Opportunity_Created_Date              datetime64[ns]
Quote_Expiry_Date                     datetime64[ns]
Last_Modified_Date                    datetime64[ns]
Last_Modified_By                              object
Product_Family                                object
Product_Name                                  object
ASP_Currency                                  object
ASP                                          float64
ASP_(converted)_Currency                      object
                                           ...
ASP_(converted)_sum                          float64
ASP_(converted)_mean                         float64
ASP_(converted)_median                       float64
ASP_(converted)_std                          float64
ASP_(converted)_max                          float64
ASP_(converted)_min                          float64
TRF_sum                                        int64
TRF_mean                                     float64
TRF_median                                   float64
TRF_std                                      float64
TRF_max                                        int64
TRF_min                                        int64
Total_Amount_sum                             float64
Total_Amount_mean                            float64
Total_Amount_median                          float64
Total_Amount_std                             float64
Total_Amount_max                             float64
Total_Amount_min                             float64
Total_Taxable_Amount_sum                     float64
Total_Taxable_Amount_mean                    float64
Total_Taxable_Amount_median                  float64
Total_Taxable_Amount_std                     float64
Total_Taxable_Amount_max                     float64
Total_Taxable_Amount_min                     float64
Total_Amount_converted_sum                   float64
Total_Amount_converted_mean                  float64
Total_Amount_converted_median                float64
Total_Amount_converted_std                   float64
Total_Amount_converted_max                   float64
Total_Amount_converted_min                   float64
Length: 83, dtype: object

# Gererador de features cumulative para categoricas

In [19]:
dataset['ganado']= (dataset['Stage']== 'Closed Won')
dataset['counter']= 1
categorical = ['Region', 'Territory', 'Product_Name', 'Account_Owner',
               'Bureaucratic_Code','Billing_Country', 'Account_Name',
               'Opportunity_Owner','Quote_Type', 'Delivery_Terms',
               'Last_Modified_By', 'Product_Family', 'Month', 'Delivery_Quarter']
for agrupador in categorical:
    gruped_product = dataset.groupby(agrupador)[['ganado','counter']].cumsum()
    gruped_product[agrupador + '_mean'] = gruped_product['ganado']/ gruped_product['counter']
    gruped_product= gruped_product.rename(columns = {'ganado':(agrupador + '_ganados'), 'counter': (agrupador + '_count') })
    dataset= dataset.join(gruped_product)

In [20]:
dataset.dtypes

ID                                             int64
Region                                        object
Territory                                     object
Pricing, Delivery_Terms_Quote_Appr             int64
Pricing, Delivery_Terms_Approved               int64
Bureaucratic_Code_0_Approval                   int64
Bureaucratic_Code_0_Approved                   int64
Bureaucratic_Code                             object
Account_Created_Date                  datetime64[ns]
Source                                        object
Billing_Country                               object
Account_Name                                  object
Opportunity_Name                              object
Opportunity_ID                                 int64
Sales_Contract_No                             object
Account_Owner                                 object
Opportunity_Owner                             object
Account_Type                                  object
Opportunity_Type                              object
Quote_Type                                    object
Delivery_Terms                                object
Opportunity_Created_Date              datetime64[ns]
Quote_Expiry_Date                     datetime64[ns]
Last_Modified_Date                    datetime64[ns]
Last_Modified_By                              object
Product_Family                                object
Product_Name                                  object
ASP_Currency                                  object
ASP                                          float64
ASP_(converted)_Currency                      object
                                           ...
Bureaucratic_Code_ganados                    float64
Bureaucratic_Code_count                        int64
Bureaucratic_Code_mean                       float64
Billing_Country_ganados                      float64
Billing_Country_count                          int64
Billing_Country_mean                         float64
Account_Name_ganados                         float64
Account_Name_count                             int64
Account_Name_mean                            float64
Opportunity_Owner_ganados                    float64
Opportunity_Owner_count                        int64
Opportunity_Owner_mean                       float64
Quote_Type_ganados                           float64
Quote_Type_count                               int64
Quote_Type_mean                              float64
Delivery_Terms_ganados                       float64
Delivery_Terms_count                           int64
Delivery_Terms_mean                          float64
Last_Modified_By_ganados                     float64
Last_Modified_By_count                         int64
Last_Modified_By_mean                        float64
Product_Family_ganados                       float64
Product_Family_count                           int64
Product_Family_mean                          float64
Month_ganados                                float64
Month_count                                    int64
Month_mean                                   float64
Delivery_Quarter_ganados                     float64
Delivery_Quarter_count                         int64
Delivery_Quarter_mean                        float64
Length: 127, dtype: object

# categorical de a pares

In [21]:
for i in range(len(categorical) -1):
    for j in range(i +1, len(categorical)):
        gruped_product = dataset.groupby([categorical[i],categorical[j]])[['ganado','counter']].cumsum()
        gruped_product[categorical[i] + '_'+ categorical[j] + '_mean'] = gruped_product['ganado']/ gruped_product['counter']
        gruped_product= gruped_product.rename(columns = {'ganado':(categorical[i] + '_'+ categorical[j] + '_ganados'), 'counter': (categorical[i] + '_'+ categorical[j] + '_count') })
        dataset= dataset.join(gruped_product)

In [22]:
dataset.dtypes

ID                                                    int64
Region                                               object
Territory                                            object
Pricing, Delivery_Terms_Quote_Appr                    int64
Pricing, Delivery_Terms_Approved                      int64
Bureaucratic_Code_0_Approval                          int64
Bureaucratic_Code_0_Approved                          int64
Bureaucratic_Code                                    object
Account_Created_Date                         datetime64[ns]
Source                                               object
Billing_Country                                      object
Account_Name                                         object
Opportunity_Name                                     object
Opportunity_ID                                        int64
Sales_Contract_No                                    object
Account_Owner                                        object
Opportunity_Owner                                    object
Account_Type                                         object
Opportunity_Type                                     object
Quote_Type                                           object
Delivery_Terms                                       object
Opportunity_Created_Date                     datetime64[ns]
Quote_Expiry_Date                            datetime64[ns]
Last_Modified_Date                           datetime64[ns]
Last_Modified_By                                     object
Product_Family                                       object
Product_Name                                         object
ASP_Currency                                         object
ASP                                                 float64
ASP_(converted)_Currency                             object
                                                  ...
Delivery_Terms_Last_Modified_By_ganados             float64
Delivery_Terms_Last_Modified_By_count                 int64
Delivery_Terms_Last_Modified_By_mean                float64
Delivery_Terms_Product_Family_ganados               float64
Delivery_Terms_Product_Family_count                   int64
Delivery_Terms_Product_Family_mean                  float64
Delivery_Terms_Month_ganados                        float64
Delivery_Terms_Month_count                            int64
Delivery_Terms_Month_mean                           float64
Delivery_Terms_Delivery_Quarter_ganados             float64
Delivery_Terms_Delivery_Quarter_count                 int64
Delivery_Terms_Delivery_Quarter_mean                float64
Last_Modified_By_Product_Family_ganados             float64
Last_Modified_By_Product_Family_count                 int64
Last_Modified_By_Product_Family_mean                float64
Last_Modified_By_Month_ganados                      float64
Last_Modified_By_Month_count                          int64
Last_Modified_By_Month_mean                         float64
Last_Modified_By_Delivery_Quarter_ganados           float64
Last_Modified_By_Delivery_Quarter_count               int64
Last_Modified_By_Delivery_Quarter_mean              float64
Product_Family_Month_ganados                        float64
Product_Family_Month_count                            int64
Product_Family_Month_mean                           float64
Product_Family_Delivery_Quarter_ganados             float64
Product_Family_Delivery_Quarter_count                 int64
Product_Family_Delivery_Quarter_mean                float64
Month_Delivery_Quarter_ganados                      float64
Month_Delivery_Quarter_count                          int64
Month_Delivery_Quarter_mean                         float64
Length: 400, dtype: object